name: Cloud 189 Check In
on:
  workflow_dispatch:
  push:
    branches:
      - main
  watch:
    types: started
  schedule:
    # UTC时间每天0点（中国时间早上8点）执行。 注意，这个时间通常会有延迟，甚至推迟一个小时，取决于 GitHub 的调度队列。
    - cron: 0 0 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: init
        run: npm install
      - name: run
        id: run
        uses: nick-fields/retry@v2
        env:
          TY_USER_NAME: ${{secrets.TY_USER_NAME}}
          TY_PASSWORD: ${{secrets.TY_PASSWORD}}
          TY_USER_NAME1: ${{secrets.TY_USER_NAME1}}
          TY_PASSWORD1: ${{secrets.TY_PASSWORD1}}
          TY_USER_NAME2: ${{secrets.TY_USER_NAME2}}
          TY_PASSWORD2: ${{secrets.TY_PASSWORD2}}
          TY_USER_NAM3: ${{secrets.TY_USER_NAM3}}
          TY_PASSWORD3: ${{secrets.TY_PASSWORD3}}
          TY_USER_NAME4: ${{secrets.TY_USER_NAME4}}
          TY_PASSWORD4: ${{secrets.TY_PASSWORD4}}
          # Server
          SENDKEY: ${{secrets.SENDKEY}}
          # pushdeer
          PUSHDEER_PUSH_KEY: ${{secrets.PUSHDEER_PUSH_KEY}}
          # Telegram
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm start
